Помощь друга
htmlacademy-javascript/1664351-keksobooking-24 pull request #9
Opened 2021-10-25 19:35 UTC by Michaverkh

---
:mortar_board: [Помощь друга](https://up.htmlacademy.ru/javascript/24/user/1664351/tasks/18)

:boom: https://htmlacademy-javascript.github.io/1664351-keksobooking-24/9/

2021-11-01 14:46 UTC, bzvyagintsev requested changes

2021-11-01 14:46 UTC, bzvyagintsev commented on js/alert-message.js
> +const showAlert = (message) => {
Это типа ошибка? А там случайно в разметке нет для этого уже шаблона?

2021-11-01 14:46 UTC, bzvyagintsev commented on js/api.js
> +    })
Эту логику надо вызывать там, где ты вызываешь функцию getData

2021-11-01 14:46 UTC, bzvyagintsev commented on js/api.js
> +    evt.preventDefault();
Обрабатывай сабмит там где у тебя логика с формой. 

Эта функция у тебя должна обрабатывать отправку данных через фетч.

А сейчас, у тебя внутри этой функции вызывается установка обработчика события. Скорее всего поэтому отправка и глючит: функция должны отправлять данные, а она при каждом вызове создаёт обработчик события, который ещё должен когда-то запуститься.

2021-11-01 14:46 UTC, bzvyagintsev commented on js/api.js
> +        closePopups();
Вот эту логику тоже надо вынести в то место, где ты вызываешь setUserFormSubmit. Например, добавить это всё внутрь функции onSuccess()

2021-11-01 14:46 UTC, bzvyagintsev commented on js/card-creation.js
> +  // eslint-disable-next-line no-prototype-builtins
Не отключай линтер. Если он тебе что-то подчёркивает — это ошибка.

2021-11-01 14:46 UTC, bzvyagintsev commented on js/card-creation.js
> +  // eslint-disable-next-line no-prototype-builtins
Не отключай линтер. Если он тебе что-то подчёркивает — это ошибка.

2021-11-01 14:46 UTC, bzvyagintsev commented on js/error-modal.js
> +};
Не удаляешь обработчики:
document.addEventListener('keydown', onPopupEscKeydown);
document.addEventListener('click', onPopupClick);

2021-11-01 14:46 UTC, bzvyagintsev commented on js/map.js
> +    // eslint-disable-next-line no-shadow
Попробуй решить эту ошибку

2021-11-01 14:46 UTC, bzvyagintsev commented on js/success-modal.js
> +};
1. Не удаляешь обработчики событий
2. Не блокируешь скрол на body

2021-11-01 14:46 UTC, bzvyagintsev commented on js/error-modal.js
> +};
Не блокируешь скрол на body

2021-11-01 14:47 UTC, merged

2021-11-02 03:46 UTC, Michaverkh commented on js/alert-message.js
> +const showAlert = (message) => {
В разметке есть шаблон только для неудачной отправки формы. При неудачной загрузке данных, сообщение нужно придумать самостоятельно, согласно тз